name: Publish

on:
  push: # Will trigger when the RELEASES.md file is updated by the merged PR from the generation workflow
    paths:
      - 'RELEASES.md'
    branches:
      - main

jobs:
  publish:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v14 # Import the SDK publishing workflow to handle publishing to the package managers
    with:
      publish_java: true # Tells the publishing action to publish the Java SDK to Maven Central
      create_release: true
      use_sonatype_central: true
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
      java_gpg_secret_key: ${{ secrets.JAVA_GPG_SECRET_KEY }}
      java_gpg_passphrase: ${{ secrets.JAVA_GPG_PASSPHRASE }}
      ossrh_username: ${{ secrets.OSSRH_USERNAME }}
      ossrh_password: ${{ secrets.OSSRH_PASSWORD }}
